import * as vscode from 'vscode';
import * as path from 'path';

export class ClangdConfigEditorProvider implements vscode.CustomTextEditorProvider {

    public static readonly viewType = 'clangd.configEditor';

    public static register(context: vscode.ExtensionContext): vscode.Disposable {
        const provider = new ClangdConfigEditorProvider(context);
        const providerRegistration = vscode.window.registerCustomEditorProvider(ClangdConfigEditorProvider.viewType, provider);
        return providerRegistration;
    }

    constructor(
        private readonly context: vscode.ExtensionContext
    ) { }

    public async resolveCustomTextEditor(
        document: vscode.TextDocument,
        webviewPanel: vscode.WebviewPanel,
        _token: vscode.CancellationToken
    ): Promise<void> {
        webviewPanel.webview.options = {
            enableScripts: true,
            localResourceRoots: [
                vscode.Uri.file(path.join(this.context.extensionPath, 'out', 'webview'))
            ]
        };

        webviewPanel.webview.html = await this.getHtmlForWebview(webviewPanel.webview);

        function updateWebview() {
            webviewPanel.webview.postMessage({
                type: 'update',
                text: document.getText(),
            });
        }

        const changeDocumentSubscription = vscode.workspace.onDidChangeTextDocument(e => {
            if (e.document.uri.toString() === document.uri.toString()) {
                updateWebview();
            }
        });

        webviewPanel.onDidDispose(() => {
            changeDocumentSubscription.dispose();
        });

        webviewPanel.webview.onDidReceiveMessage(e => {
            switch (e.type) {
                case 'change':
                    this.updateTextDocument(document, e.text);
                    return;
                case 'ready':
                    updateWebview();
                    return;
            }
        });
    }

    private async getHtmlForWebview(webview: vscode.Webview): Promise<string> {
        const distPath = path.join(this.context.extensionPath, 'out', 'webview');
        const indexHtmlPath = path.join(distPath, 'index.html');
        
        let html: string;
        try {
            const indexHtmlUri = vscode.Uri.file(indexHtmlPath);
            const indexHtmlData = await vscode.workspace.fs.readFile(indexHtmlUri);
            html = new TextDecoder().decode(indexHtmlData);
        } catch (e) {
            console.error('Failed to load Webview HTML', e);
            return `<div>Error loading Webview: ${e}</div>`;
        }

        // Convert relative paths to Webview URIs
        // The index.html generated by Vite uses ./assets/..., we need to replace ./ with the webview uri base
        const webviewBaseUri = webview.asWebviewUri(vscode.Uri.file(distPath));
        
        // Simple replacement for ./assets/
        html = html.replace(
            /(src|href)="\.\/assets\//g, 
            `$1="${webviewBaseUri.toString()}/assets/`
        );
        
        return html;
    }

    private updateTextDocument(document: vscode.TextDocument, text: string) {
        if (document.getText() === text) {
             return;
        }
        const edit = new vscode.WorkspaceEdit();
        edit.replace(
            document.uri,
            new vscode.Range(0, 0, document.lineCount, 0),
            text
        );
        vscode.workspace.applyEdit(edit);
    }
}
